Feat/new ab in js
Mil0dV/co2ok-plugin-woocommerce pull request #42
Opened 2020-09-21 10:23 UTC by Ghostyfied

2020-09-21 10:30 UTC, Ghostyfied commented
**Testing:**

-

2020-09-21 14:31 UTC, Mil0dV requested changes

2020-09-21 14:31 UTC, Mil0dV commented on co2ok-plugin.php
> +                            setcookie('co2ok_ab_init', 1, time()+900);
Slightly nitpicking as well, but I think ab_init won't be that understandable for future coders. Perhaps `_enabled`?

Cookie could live longer as well, I'd say a day.

2020-09-21 14:31 UTC, Mil0dV commented on co2ok-plugin.php
> +                    setcookie('co2ok_ab_init', 0, time()+900);
This shouldn't be necessary - if the code on the other end sees an absent cookie as false.

2020-09-21 14:31 UTC, Mil0dV commented on co2ok-plugin.php
> +                        if (Co2ok_JS().getCookieValue('co2ok_hide_test') % 2 == 0) {
` % 2 == 0` isn't needed here.

2020-09-21 14:31 UTC, Mil0dV commented on js/co2ok-plugin.js
> +    var ID = Math.round(Math.random());
ID is bit of a misnomer - it's just a boolean right?

2020-09-21 14:31 UTC, Mil0dV commented on js/co2ok-plugin.js
> +  if (Co2ok_JS().getCookieValue('co2ok_ab_init') == 1 && document.cookie.match(/^(.*;)?\s*co2ok_hide_test\s*=\s*[^;]+(.*)?$/)){
Couldn't you use getCookieValue twice here? 

I also think this if, the one on #685 (is that necessary?) and the else if on #691 need another look/think. It seems the remove() doesn't get called after #696 sets hide_test to 1.

2020-09-21 14:31 UTC, Mil0dV commented on co2ok-plugin.php
> +                    // if (is_user_logged_in()){
This code can go - git has our history.

2020-09-22 13:29 UTC, jdsmith022 commented on co2ok-plugin.php
> +                        }
Didn't we want the cookie to live longer? Re: Previous comment from @Mil0dV

2020-09-29 15:53 UTC, Mil0dV requested changes

2020-09-29 15:53 UTC, Mil0dV commented on js/co2ok-plugin.js
> +  if (Co2ok_JS().getCookieValue('co2ok_ab_enabled') == 1 && !Co2ok_JS().getCookieValue('co2ok_ab_hide'))
Since this is a pretty critical part of our code, I'd say a little documentation is in order :)

2020-09-29 15:53 UTC, Mil0dV commented on js/co2ok-plugin.js
> +    var boolean = Math.round(Math.random());
It _is_ a boolean, but what is it's purpose?

2020-09-29 15:53 UTC, Mil0dV commented on js/co2ok-plugin.js
> +    document.cookie = "co2ok_ab_hide=" + boolean + "; expires=" + now.toUTCString() + "; path=/";
now.toUTCString() is pretty confusing to me - I had to read back to figure out you're travelling to the future. I would say something like this:
```
var tomorrow = new Date();
tomorrow.setDate(new Date().getDate()+1);
tomorrow.toUTCString()
```

(first line 'tomorrow' is still lying, but there doesn't seem to be a way around it)

2020-09-30 09:48 UTC, merged

2020-10-02 14:38 UTC, Mil0dV commented on js/co2ok-plugin.js
> +    if (Co2ok_JS().getCookieValue('co2ok_ab_hide') % 2 == 0)
this could be moved into the if statement from #684