Feat/currency string adjustment
Mil0dV/co2ok-plugin-woocommerce pull request #43
Opened 2020-10-20 10:41 UTC by jdsmith022

Font size of currency and make are not relative to the length of the currency string. Did a little refactoring as well as applied consistency throughout code

Tested in all themes in WC-test.co2ok.eco

**Sample Result:**

<img width="617" alt="Screen Shot 2020-10-20 at 12 39 19 PM" src="https://user-images.githubusercontent.com/45078521/96575652-534dbb00-12d1-11eb-81e0-234d34b01446.png">
<img width="778" alt="Screen Shot 2020-10-20 at 12 35 47 PM" src="https://user-images.githubusercontent.com/45078521/96575510-1e416880-12d1-11eb-82e1-0ed21b8d7eb4.png">
<img width="713" alt="Screen Shot 2020-10-20 at 12 35 55 PM" src="https://user-images.githubusercontent.com/45078521/96575515-200b2c00-12d1-11eb-8284-a776d5c59f35.png">
<img width="657" alt="Screen Shot 2020-10-20 at 12 36 30 PM" src="https://user-images.githubusercontent.com/45078521/96575522-213c5900-12d1-11eb-9b90-461df26845e9.png">
<img width="718" alt="Screen Shot 2020-10-20 at 12 36 43 PM" src="https://user-images.githubusercontent.com/45078521/96575524-21d4ef80-12d1-11eb-9662-1803ae30324e.png">
<img width="695" alt="Screen Shot 2020-10-20 at 12 37 24 PM" src="https://user-images.githubusercontent.com/45078521/96575578-34e7bf80-12d1-11eb-9e5a-e87db2d7d036.png">
<img width="712" alt="Screen Shot 2020-10-20 at 12 37 31 PM" src="https://user-images.githubusercontent.com/45078521/96575584-374a1980-12d1-11eb-97a7-930b200fd111.png">

<img width="659" alt="Screen Shot 2020-10-20 at 12 39 31 PM" src="https://user-images.githubusercontent.com/45078521/96575661-55177e80-12d1-11eb-9585-5985bc8af7da.png">

Discrepancies found for two themes: 

Woodmart: 
minimal: 
<img width="436" alt="Screen Shot 2020-10-20 at 12 25 13 PM" src="https://user-images.githubusercontent.com/45078521/96574986-775ccc80-12d0-11eb-9eb1-411b6a5a2544.png">
default:
<img width="261" alt="Screen Shot 2020-10-20 at 12 30 08 PM" src="https://user-images.githubusercontent.com/45078521/96575012-7e83da80-12d0-11eb-8f47-bdd487ec19a1.png">

27:
default:
<img width="305" alt="Screen Shot 2020-10-20 at 11 31 25 AM" src="https://user-images.githubusercontent.com/45078521/96575023-82176180-12d0-11eb-861f-e952a4cc4c6c.png">

2020-10-20 18:22 UTC, Mil0dV requested changes
Was it necessary to shrink 'Make' and the logo? I'd prefer to only shrink the amount unless that looks weird/leads to side effects. 

Ideally we could then clean up default- and minimalButton some more (e.g. the else shouldn't be needed since those values are in the css, right?)

2020-10-20 18:22 UTC, Mil0dV commented on css/co2ok.css
> +      margin-top: 9px;
Usually, the `!important`'s are there for a reason. Sometimes finding the corresponding commit with `git blame` tells us why we had to include the important. 

In general I would not remove them unless necessary.

2020-10-20 18:32 UTC, Mil0dV requested changes

2020-10-20 18:32 UTC, Mil0dV commented on js/co2ok-plugin.js
> +  var relative_font_size;
in JS you don't need to declare vars first :)

2020-10-20 18:32 UTC, Mil0dV commented on js/co2ok-plugin.js
> +                    if(document.querySelector('.qty') != null) {
this can go, right? (and some code below too)

2020-10-21 10:20 UTC, jdsmith022 commented
removed more unnecessary code left over from .qty and .quantity-product. removed else statements from minimalButton() and defaultButton() and added few style changes into css instead.

2020-10-22 09:40 UTC, Ghostyfied approved these changes

2020-10-22 09:53 UTC, Ghostyfied commented on js/co2ok-plugin.js
> +                        defaultButton();
Does this work without scope??

2020-10-22 09:53 UTC, Ghostyfied commented on js/co2ok-plugin.js
> +                        minimumButton();
same ^^

2020-10-22 09:58 UTC, Mil0dV requested changes
Only fix if it's very quick

2020-10-22 09:58 UTC, Mil0dV commented on css/co2ok.css
> +      margin-top: 9px;
This works in my dev tools:
```
var element = document.querySelector('.compensation_amount_default');
element.setAttribute( 'style', 'font-size: 23px !important' );
```

But if that still gives issues, let's leave it - I think our previous code already reset the !importants :)

2020-10-22 09:59 UTC, Mil0dV commented on js/co2ok-plugin.js
> +                        defaultButton();
The WC plugin JS is a mess - this function is defined at the top level - global scope.

2020-10-22 10:49 UTC, jdsmith022 commented on css/co2ok.css
> +      margin-top: 9px;
Yes, I tried this and also `element.style.cssText = 'font-size: 22px !important';` and it wouldn't overwrite the css

2020-10-22 10:49 UTC, jdsmith022 commented on js/co2ok-plugin.js
> +                        defaultButton();
^^ yep

2020-10-26 13:49 UTC, Mil0dV approved these changes

2020-10-26 14:35 UTC, merged

2021-12-07 21:46 UTC, TheApeMachine commented on css/co2ok.css
> +      margin-top: 9px;
https://css-tricks.com/fitting-text-to-a-container/ why not just do it in CSS and avoid the complexity of a JS solution...