Feat/bewust bezorgd
Mil0dV/co2ok-plugin-woocommerce pull request #49
Opened 2021-03-15 14:01 UTC by jdsmith022

Implementation of Bewust Bezorgd, 
Use of plugin without comp button, and 
Only load middleware on WC pages

Bewust Bezorgd implemented for WC -> added function updateMerchant to sent GraphQL query to backend to request and return store's BB Api id and password which is then added as option

added check that page is either a WC page, cart or checkout page. If true, middleware is loaded

added switch for hidden feature of hiding comp button in store

2021-03-23 12:00 UTC, Mil0dV commented on co2ok-plugin.php
> +            $query->setFunctionReturnTypes(array("bbShopid", "bbPassword"));
The backend expects snake_case, then the query should get results

2021-04-06 12:39 UTC, jdsmith022 commented on co2ok-plugin.php
> +            $query->setFunctionReturnTypes(array("bbShopid", "bbPassword"));
Did a check with this id and secret and received hoi back: 
<img width="1013" alt="Screenshot 2021-04-06 at 2 38 42 PM" src="https://user-images.githubusercontent.com/45078521/113711991-e181f600-96e5-11eb-85d0-c3556ffb0ec8.png">

2021-04-16 11:08 UTC, mvhou commented on Components/Co2ok-BewustBezorgd.php
> +
I'm not 100% sure what's happening here. It checks if the last two characters in the shop's post code are letters, and if not it concatenates JS?

2021-04-16 11:11 UTC, jdsmith022 commented on Components/Co2ok-BewustBezorgd.php
> +
Yes, there are sometimes issues with the postcode. BB API only works with NL post codes so we have a check for that, but somehow there a times when the postcode won't have letter to it...how the order gets through, we don't know, so this checks if there are letters attached to the post code, if not we attach JS.

2021-04-16 12:14 UTC, Mil0dV requested changes

2021-04-16 12:14 UTC, Mil0dV commented on co2ok-plugin.php
> +    final private function co2ok_bewust_bezorgd($order, $merchantId) {
`co2ok_bewust_bezorgd()` doesn't say what this function _does_.

2021-04-16 12:14 UTC, Mil0dV commented on co2ok-plugin.php
> +                    Co2ok_Plugin::remoteLogging(json_encode(["Order delivery or store outside of NL. Delivery country ", $orderDetails]));
On second thought I don't think it's very useful to log this remotely. Let's disable #685 for now.

2021-04-16 12:14 UTC, Mil0dV commented on co2ok-plugin.php
> +        'defer div="widgetContainerXL" merchantId=' . $code . ' widgetSize="' . $size . '" widgetColor="' . $color . '" lang="' . $lang . '"></script>';
Ah, nice! I think we should also do #1179

2021-04-16 12:42 UTC, jdsmith022 commented on Components/Co2ok-BewustBezorgd.php
> +		return 'NextDay';
added remote log for not match but will look futher into this detail on next PR

2021-04-22 08:36 UTC, Mil0dV requested changes

2021-04-22 08:36 UTC, Mil0dV commented on Components/Co2ok-BewustBezorgd.php
> +				\co2ok_plugin_woocommerce\Co2ok_Plugin::remoteLogging("Logging BB Api two-legs error response: " . $responseTwoLegs['errors'], " Emissions(g): " . $emissionsGrams, "Diesel: " . $diesel . " Gasoli
Don't we need json_encode anymore? We seem to be doing it everywhere in the code

2021-04-22 08:36 UTC, Mil0dV commented on co2ok-plugin.php
> +    final private function co2ok_bewust_bezorgd($order, $merchantId) {
I was commenting on the method name, not the lack of documentation ;)

2021-04-22 08:37 UTC, jdsmith022 commented on co2ok-plugin.php
> +    final private function co2ok_bewust_bezorgd($order, $merchantId) {
oh haha

2021-04-22 08:50 UTC, jdsmith022 commented on Components/Co2ok-BewustBezorgd.php
> +				\co2ok_plugin_woocommerce\Co2ok_Plugin::remoteLogging("Logging BB Api two-legs error response: " . $responseTwoLegs['errors'], " Emissions(g): " . $emissionsGrams, "Diesel: " . $diesel . " Gasoli
that's a good point. I did get a logs in the log entries when I tested, but let me check again

2021-05-07 09:24 UTC, merged